import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const sfPro = localFont({
  src: [
    {
      path: '../public/fonts/SFPRODISPLAYMEDIUM.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/SFPRODISPLAYBOLD.ttf',
      weight: '700', 
      style: 'normal',
    }
  ],
  variable: '--font-sf-pro'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
